import { mapObstructedTerrain } from './obstructedTerrain';

/* Details of the maps used by the levels */
const maps = {
  plains: {
    mapImage: 'plains-debug.png',

    /* Terrain Data - Auto Generated By level/convert-levels.js */
    mapGridWidth: 60,
    mapGridHeight: 40,
    mapObstructedTerrain,
  },
};

/* The actual levels played in the game */
const levels = {
  singleplayer: [
    {
      name: 'Introduction',
      briefing: "In this level you will learn how to pan across the map.\nDon't worry! We will be implementing more features soon.",

      /* Map Details */
      mapName: 'plains',

      /* Starting location for player */
      startX: 4,
      startY: 4,
    },
  ],

  multiplayer: [

  ],
};
